export interface KenyaCounty {
  code: string;           // e.g. "042", "027", "047"
  number: number;         // 1 to 47
  name: string;           // e.g. "Kisumu", "Uasin Gishu", "Nairobi"
  capital: string;        // e.g. "Kisumu City", "Eldoret", "Nairobi CBD"
  primaryStage: string;   // e.g. "Kisumu Central Bus Park", "Eldoret Zion Mall Stage", "Nairobi OTC / Tea Room"
  region: 'Nyanza & Lake Basin' | 'Western Region' | 'North Rift & South Rift' | 'Nairobi & Central' | 'Mount Kenya & Eastern' | 'Coast Corridor' | 'North Eastern';
  transitHours: string;   // e.g. "Same-Day (2-3 hrs)", "Overnight (6-7 hrs)", "Morning (8 hrs)"
  recommendedCouriers: string[];
  popularDropPoints: string[];
}

export const KENYA_47_COUNTIES: KenyaCounty[] = [
  // 001 - 006 Coast Corridor
  {
    code: '001',
    number: 1,
    name: 'Mombasa',
    capital: 'Mombasa City',
    primaryStage: 'Mwembe Tayari / Bondeni Bus Terminal',
    region: 'Coast Corridor',
    transitHours: 'Overnight (14-16 hrs)',
    recommendedCouriers: ['Guardian Angel', 'Tahmeed Coach', 'Simba Coach', 'Fargo Courier'],
    popularDropPoints: ['Mwembe Tayari', 'Nyali', 'Changamwe', 'Likoni Ferry', 'Bamburi'],
  },
  {
    code: '002',
    number: 2,
    name: 'Kwale',
    capital: 'Kwale Town / Ukunda',
    primaryStage: 'Ukunda Diani Stage',
    region: 'Coast Corridor',
    transitHours: 'Overnight (16 hrs)',
    recommendedCouriers: ['Tahmeed Coach', 'Guardian Angel', 'Fargo Courier'],
    popularDropPoints: ['Ukunda', 'Diani Beach Road', 'Kwale Town', 'Lunga Lunga Border'],
  },
  {
    code: '003',
    number: 3,
    name: 'Kilifi',
    capital: 'Kilifi Town / Malindi',
    primaryStage: 'Malindi Bus Terminal / Kilifi Stage',
    region: 'Coast Corridor',
    transitHours: 'Overnight (16-18 hrs)',
    recommendedCouriers: ['Tahmeed Coach', 'Guardian Angel', 'Fargo Courier'],
    popularDropPoints: ['Malindi Town', 'Kilifi Bridge Stage', 'Mtwapa Junction', 'Mariakani'],
  },
  {
    code: '004',
    number: 4,
    name: 'Tana River',
    capital: 'Hola',
    primaryStage: 'Hola Bus Stage',
    region: 'Coast Corridor',
    transitHours: '24 hrs (via Mombasa / Nairobi)',
    recommendedCouriers: ['Fargo Courier', 'Posta EMS'],
    popularDropPoints: ['Hola Town', 'Garsen Junction', 'Bura'],
  },
  {
    code: '005',
    number: 5,
    name: 'Lamu',
    capital: 'Lamu Island / Mokowe',
    primaryStage: 'Mokowe Jetty Terminal',
    region: 'Coast Corridor',
    transitHours: '24 hrs Express',
    recommendedCouriers: ['Tahmeed Coach', 'Fargo Courier'],
    popularDropPoints: ['Mokowe Mainland', 'Lamu Island', 'Mpeketoni'],
  },
  {
    code: '006',
    number: 6,
    name: 'Taita Taveta',
    capital: 'Voi / Wundanyi',
    primaryStage: 'Voi Highway Bus Terminal',
    region: 'Coast Corridor',
    transitHours: 'Overnight (12-14 hrs)',
    recommendedCouriers: ['Guardian Angel', 'Tahmeed Coach', 'Fargo Courier'],
    popularDropPoints: ['Voi Caltex Stage', 'Taveta Border', 'Wundanyi Town', 'Mwatate'],
  },

  // 007 - 009 North Eastern
  {
    code: '007',
    number: 7,
    name: 'Garissa',
    capital: 'Garissa Town',
    primaryStage: 'Garissa Main Stage & Kismayu Rd',
    region: 'North Eastern',
    transitHours: 'Next-Day (18 hrs via Nairobi)',
    recommendedCouriers: ['Ena Coach', 'Moyale Liner', 'Fargo Courier'],
    popularDropPoints: ['Garissa CBD', 'Madogo Stage', 'Dadaab Junction'],
  },
  {
    code: '008',
    number: 8,
    name: 'Wajir',
    capital: 'Wajir Town',
    primaryStage: 'Wajir Bus Terminal',
    region: 'North Eastern',
    transitHours: '24-36 hrs Express',
    recommendedCouriers: ['Wajir Express', 'Fargo Courier'],
    popularDropPoints: ['Wajir Town Centre', 'Habaswein', 'Buna'],
  },
  {
    code: '009',
    number: 9,
    name: 'Mandera',
    capital: 'Mandera Town',
    primaryStage: 'Mandera Central Stage',
    region: 'North Eastern',
    transitHours: '36-48 hrs Parcel Route',
    recommendedCouriers: ['Moyale Liner', 'Fargo Courier'],
    popularDropPoints: ['Mandera CBD', 'Rhamu', 'Elwak'],
  },

  // 010 - 015 Mount Kenya & Eastern
  {
    code: '010',
    number: 10,
    name: 'Marsabit',
    capital: 'Marsabit Town / Moyale',
    primaryStage: 'Marsabit Town Stage & Moyale Border Post',
    region: 'Mount Kenya & Eastern',
    transitHours: '24 hrs Express',
    recommendedCouriers: ['Moyale Liner', 'Fargo Courier'],
    popularDropPoints: ['Marsabit CBD', 'Moyale Border Stage', 'Sololo'],
  },
  {
    code: '011',
    number: 11,
    name: 'Isiolo',
    capital: 'Isiolo Town',
    primaryStage: 'Isiolo Main Stage (Moyale Highway)',
    region: 'Mount Kenya & Eastern',
    transitHours: 'Next-Day (12-14 hrs via Nakuru)',
    recommendedCouriers: ['Guardian Angel', 'Ena Coach', 'Fargo Courier'],
    popularDropPoints: ['Isiolo CBD', 'Archer\'s Post Junction'],
  },
  {
    code: '012',
    number: 12,
    name: 'Meru',
    capital: 'Meru Town',
    primaryStage: 'Meru Makutano Bus Terminal',
    region: 'Mount Kenya & Eastern',
    transitHours: 'Overnight / Next Morning (10-12 hrs)',
    recommendedCouriers: ['Guardian Angel', 'Ena Coach', 'Fargo Courier'],
    popularDropPoints: ['Meru Town Makutano', 'Maua Town', 'Nkubu Stage', 'Timau'],
  },
  {
    code: '013',
    number: 13,
    name: 'Tharaka Nithi',
    capital: 'Chuka / Kathwana',
    primaryStage: 'Chuka University Stage',
    region: 'Mount Kenya & Eastern',
    transitHours: 'Overnight (10-12 hrs)',
    recommendedCouriers: ['Guardian Angel', 'Ena Coach', 'Fargo Courier'],
    popularDropPoints: ['Chuka Town Stage', 'Kathwana', 'Marimanti'],
  },
  {
    code: '014',
    number: 14,
    name: 'Embu',
    capital: 'Embu Town',
    primaryStage: 'Embu Main Bus Park',
    region: 'Mount Kenya & Eastern',
    transitHours: 'Overnight (9-10 hrs)',
    recommendedCouriers: ['Guardian Angel', 'Ena Coach', 'Fargo Courier'],
    popularDropPoints: ['Embu CBD', 'Runyenjes', 'Siakago'],
  },
  {
    code: '015',
    number: 15,
    name: 'Kitui',
    capital: 'Kitui Town',
    primaryStage: 'Kitui Central Bus Stage',
    region: 'Mount Kenya & Eastern',
    transitHours: 'Overnight (10-12 hrs)',
    recommendedCouriers: ['Guardian Angel', 'Fargo Courier'],
    popularDropPoints: ['Kitui Town CBD', 'Mwingi Stage', 'Mutomo'],
  },
  {
    code: '016',
    number: 16,
    name: 'Machakos',
    capital: 'Machakos Town',
    primaryStage: 'Machakos People\'s Park Stage',
    region: 'Mount Kenya & Eastern',
    transitHours: 'Overnight (8-9 hrs)',
    recommendedCouriers: ['Guardian Angel', 'Easy Coach', 'Fargo Courier'],
    popularDropPoints: ['Machakos Town', 'Mlolongo', 'Athi River', 'Tala / Kangundo'],
  },
  {
    code: '017',
    number: 17,
    name: 'Makueni',
    capital: 'Wote / Mtito Andei',
    primaryStage: 'Wote Stage / Mtito Andei Highway Stop',
    region: 'Mount Kenya & Eastern',
    transitHours: 'Overnight (10-11 hrs)',
    recommendedCouriers: ['Guardian Angel', 'Tahmeed Coach', 'Fargo Courier'],
    popularDropPoints: ['Wote Town', 'Mtito Andei Highway Stage', 'Emali Junction', 'Kibwezi'],
  },

  // 018 - 022 Nairobi & Central
  {
    code: '018',
    number: 18,
    name: 'Nyandarua',
    capital: 'Ol Kalou / Engineer',
    primaryStage: 'Ol Kalou Bus Park',
    region: 'Nairobi & Central',
    transitHours: 'Overnight (6-7 hrs)',
    recommendedCouriers: ['Guardian Angel', 'Fargo Courier'],
    popularDropPoints: ['Ol Kalou Town', 'Nyahururu Stage', 'Engineer Town'],
  },
  {
    code: '019',
    number: 19,
    name: 'Nyeri',
    capital: 'Nyeri Town / Karatina',
    primaryStage: 'Nyeri Bus Park / Karatina Open Air Market Stage',
    region: 'Nairobi & Central',
    transitHours: 'Overnight (8-9 hrs)',
    recommendedCouriers: ['Guardian Angel', 'Ena Coach', 'Fargo Courier'],
    popularDropPoints: ['Nyeri CBD Stage', 'Karatina Market Stage', 'Othaya', 'Mukurweini'],
  },
  {
    code: '020',
    number: 20,
    name: 'Kirinyaga',
    capital: 'Kerugoya / Kutus',
    primaryStage: 'Kerugoya Stage / Wang\'uru Mwea',
    region: 'Nairobi & Central',
    transitHours: 'Overnight (8-9 hrs)',
    recommendedCouriers: ['Guardian Angel', 'Ena Coach', 'Fargo Courier'],
    popularDropPoints: ['Kerugoya Town', 'Mwea Wang\'uru Stage', 'Kutus Stage', 'Sagana'],
  },
  {
    code: '021',
    number: 21,
    name: 'Murang\'a',
    capital: 'Murang\'a Town / Kenol',
    primaryStage: 'Kenol Junction / Murang\'a Main Stage',
    region: 'Nairobi & Central',
    transitHours: 'Overnight (7-8 hrs)',
    recommendedCouriers: ['Guardian Angel', 'Ena Coach', 'Fargo Courier'],
    popularDropPoints: ['Kenol Flyover', 'Murang\'a Town CBD', 'Kangema', 'Maragua'],
  },
  {
    code: '022',
    number: 22,
    name: 'Kiambu',
    capital: 'Thika / Kiambu Town / Ruiru',
    primaryStage: 'Thika Main Stage / Ruiru Flyover Stage',
    region: 'Nairobi & Central',
    transitHours: 'Overnight (7 hrs)',
    recommendedCouriers: ['Guardian Angel', 'Easy Coach', 'Ena Coach', 'Fargo Courier'],
    popularDropPoints: ['Thika Town Commercial St', 'Ruiru Kamakis', 'Kikuyu Town', 'Limuru', 'Kiambu Town'],
  },

  // 023 - 036 North Rift & South Rift (Heavy Logistics Highway from Kisumu)
  {
    code: '023',
    number: 23,
    name: 'Turkana',
    capital: 'Lodwar',
    primaryStage: 'Lodwar Main Bus Terminal',
    region: 'North Rift & South Rift',
    transitHours: 'Next-Day Express (16 hrs via Kitale)',
    recommendedCouriers: ['Eldoret Express', 'Fargo Courier'],
    popularDropPoints: ['Lodwar CBD', 'Kakuma Refugee Stage', 'Lokichogio'],
  },
  {
    code: '024',
    number: 24,
    name: 'West Pokot',
    capital: 'Kapenguria / Makutano',
    primaryStage: 'Makutano Kapenguria Stage',
    region: 'North Rift & South Rift',
    transitHours: 'Morning Dispatch (6 hrs via Kitale)',
    recommendedCouriers: ['Eldoret Express', 'Easy Coach', 'Fargo Courier'],
    popularDropPoints: ['Makutano Stage', 'Kapenguria Town', 'Ortum'],
  },
  {
    code: '025',
    number: 25,
    name: 'Samburu',
    capital: 'Maralal',
    primaryStage: 'Maralal Bus Stage',
    region: 'North Rift & South Rift',
    transitHours: 'Next-Day (14 hrs via Nyahururu)',
    recommendedCouriers: ['Fargo Courier', 'Posta EMS'],
    popularDropPoints: ['Maralal CBD', 'Baragoi Stage', 'Wamba'],
  },
  {
    code: '026',
    number: 26,
    name: 'Trans Nzoia',
    capital: 'Kitale',
    primaryStage: 'Kitale Main Stage / Commercial Street',
    region: 'North Rift & South Rift',
    transitHours: 'Same-Day (3.5 - 4 hrs from Kisumu)',
    recommendedCouriers: ['Easy Coach', 'Guardian Angel', 'Eldoret Express', 'Climax Coach'],
    popularDropPoints: ['Kitale Town Commercial St', 'Kiminini Stage', 'Endebess', 'Maili Saba'],
  },
  {
    code: '027',
    number: 27,
    name: 'Uasin Gishu',
    capital: 'Eldoret City',
    primaryStage: 'Eldoret Zion Mall & Uganda Rd Stage',
    region: 'North Rift & South Rift',
    transitHours: 'Direct Express (2.5 - 3 hrs from Kisumu)',
    recommendedCouriers: ['Easy Coach', 'Guardian Angel', 'Eldoret Express', 'North Rift Shuttle', 'Climax Coach'],
    popularDropPoints: ['Eldoret CBD Uganda Rd', 'Zion Mall Terminal', 'Langas Stage', 'Huruma', 'Moi University Annex'],
  },
  {
    code: '028',
    number: 28,
    name: 'Elgeyo Marakwet',
    capital: 'Iten',
    primaryStage: 'Iten Champions Stage / Kapsowar',
    region: 'North Rift & South Rift',
    transitHours: 'Same-Day (3.5 hrs via Eldoret)',
    recommendedCouriers: ['North Rift Shuttle', 'Eldoret Express', 'Fargo Courier'],
    popularDropPoints: ['Iten Town View Point', 'Kapsowar', 'Flax', 'Chepkorio'],
  },
  {
    code: '029',
    number: 29,
    name: 'Nandi',
    capital: 'Kapsabet / Nandi Hills',
    primaryStage: 'Kapsabet Town Bus Park',
    region: 'North Rift & South Rift',
    transitHours: 'Direct Same-Day (1.5 - 2 hrs from Kisumu)',
    recommendedCouriers: ['Easy Coach', 'Kisumu Shuttles', 'Guardian Angel'],
    popularDropPoints: ['Kapsabet Town Stage', 'Nandi Hills Market', 'Mosoriot', 'Lessos'],
  },
  {
    code: '030',
    number: 30,
    name: 'Baringo',
    capital: 'Kabarnet / Eldama Ravine',
    primaryStage: 'Kabarnet Stage / Eldama Ravine Market',
    region: 'North Rift & South Rift',
    transitHours: 'Same-Day / Overnight (4-5 hrs)',
    recommendedCouriers: ['Easy Coach', 'Eldoret Express', 'Fargo Courier'],
    popularDropPoints: ['Kabarnet CBD', 'Eldama Ravine', 'Marigat Stage', 'Mogotio'],
  },
  {
    code: '031',
    number: 31,
    name: 'Laikipia',
    capital: 'Nanyuki / Rumuruti',
    primaryStage: 'Nanyuki Bus Terminal / Rumuruti Stage',
    region: 'North Rift & South Rift',
    transitHours: 'Overnight (8-9 hrs via Nakuru)',
    recommendedCouriers: ['Guardian Angel', 'Ena Coach', 'Fargo Courier'],
    popularDropPoints: ['Nanyuki Town CBD', 'Rumuruti', 'Nyahururu Stage', 'Doldol'],
  },
  {
    code: '032',
    number: 32,
    name: 'Nakuru',
    capital: 'Nakuru City / Naivasha',
    primaryStage: 'Nakuru Mash East Stage / Naivasha Bus Park',
    region: 'North Rift & South Rift',
    transitHours: 'Direct Highway (3.5 - 4 hrs from Kisumu)',
    recommendedCouriers: ['Easy Coach', 'Guardian Angel', 'Ena Coach', 'Climax Coach', 'Transline Classic'],
    popularDropPoints: ['Nakuru CBD Mash Stage', 'Naivasha Town Bus Park', 'Molo Stage', 'Gilgil', 'Njoro Post Office'],
  },
  {
    code: '033',
    number: 33,
    name: 'Narok',
    capital: 'Narok Town',
    primaryStage: 'Narok Town Highway Bus Terminal',
    region: 'North Rift & South Rift',
    transitHours: 'Same-Day / Overnight (5 hrs via Bomet)',
    recommendedCouriers: ['Transline Classic', 'Ena Coach', 'Guardian Angel'],
    popularDropPoints: ['Narok Town Main Stage', 'Kilgoris', 'Ololulung\'a', 'Maasai Mara Gate'],
  },
  {
    code: '034',
    number: 34,
    name: 'Kajiado',
    capital: 'Kajiado Town / Kitengela / Ngong',
    primaryStage: 'Kitengela Bus Stage / Ngong Town',
    region: 'North Rift & South Rift',
    transitHours: 'Overnight (7-8 hrs via Nairobi)',
    recommendedCouriers: ['Guardian Angel', 'Easy Coach', 'Fargo Courier'],
    popularDropPoints: ['Kitengela CBD', 'Ngong Town', 'Ongata Rongai', 'Kiserian', 'Namanga Border'],
  },
  {
    code: '035',
    number: 35,
    name: 'Kericho',
    capital: 'Kericho Town',
    primaryStage: 'Kericho Main Bus Park / Brooke Stage',
    region: 'North Rift & South Rift',
    transitHours: 'Direct Express (1.5 hrs from Kisumu)',
    recommendedCouriers: ['Easy Coach', 'Guardian Angel', 'Transline Classic', 'Kisumu Shuttles'],
    popularDropPoints: ['Kericho Town CBD', 'Brooke Bond Stage', 'Litein Town', 'Kipkelion'],
  },
  {
    code: '036',
    number: 36,
    name: 'Bomet',
    capital: 'Bomet Town / Sotik',
    primaryStage: 'Bomet Town Stage / Sotik Stage',
    region: 'North Rift & South Rift',
    transitHours: 'Direct Same-Day (2.5 hrs from Kisumu)',
    recommendedCouriers: ['Transline Classic', 'Ena Coach', 'Easy Coach'],
    popularDropPoints: ['Bomet Town CBD', 'Sotik Market Stage', 'Silibwet', 'Kaplong'],
  },

  // 037 - 040 Western Region (Direct Daily Hub from Kisumu)
  {
    code: '037',
    number: 37,
    name: 'Kakamega',
    capital: 'Kakamega Town',
    primaryStage: 'Kakamega Mega Mall & Central Stage',
    region: 'Western Region',
    transitHours: 'Immediate Direct (45 mins - 1 hr from Kisumu)',
    recommendedCouriers: ['Easy Coach', 'Guardian Angel', 'Climax Coach', 'Kisumu Direct Matatus'],
    popularDropPoints: ['Kakamega Mega Mall Stage', 'Mumias Town Bus Park', 'Malava', 'Lubao Market', 'Khwisero'],
  },
  {
    code: '038',
    number: 38,
    name: 'Vihiga',
    capital: 'Mbale / Chavakali',
    primaryStage: 'Mbale Bus Stage / Chavakali Junction',
    region: 'Western Region',
    transitHours: 'Immediate Direct (30 mins from Kisumu)',
    recommendedCouriers: ['Easy Coach', 'Guardian Angel', 'Kisumu Direct Matatus'],
    popularDropPoints: ['Mbale Municipal Stage', 'Chavakali Flyover', 'Luanda Market', 'Majengo Vihiga', 'Hamisi'],
  },
  {
    code: '039',
    number: 39,
    name: 'Bungoma',
    capital: 'Bungoma Town / Webuye',
    primaryStage: 'Bungoma Town Central Bus Park & Webuye Stage',
    region: 'Western Region',
    transitHours: 'Immediate Direct (1.5 - 2 hrs from Kisumu)',
    recommendedCouriers: ['Easy Coach', 'Guardian Angel', 'Climax Coach', 'Eldoret Express'],
    popularDropPoints: ['Bungoma Town Bus Park', 'Webuye Pan Paper Stage', 'Kimilili Town', 'Chwele Market', 'Malakisi'],
  },
  {
    code: '040',
    number: 40,
    name: 'Busia',
    capital: 'Busia Town / Malaba',
    primaryStage: 'Busia Customs Border Stage & Malaba Terminal',
    region: 'Western Region',
    transitHours: 'Immediate Direct (1.5 hrs from Kisumu)',
    recommendedCouriers: ['Easy Coach', 'Guardian Angel', 'Western Express', 'Climax Coach'],
    popularDropPoints: ['Busia Border Stage', 'Malaba Customs Terminal', 'Nambale Town', 'Bumala Junction', 'Port Victoria'],
  },

  // 041 - 046 Nyanza & Lake Basin (Home Turf)
  {
    code: '041',
    number: 41,
    name: 'Siaya',
    capital: 'Siaya Town / Bondo',
    primaryStage: 'Siaya Town Bus Park & Bondo Stage',
    region: 'Nyanza & Lake Basin',
    transitHours: 'Immediate Direct (1 hr from Kisumu)',
    recommendedCouriers: ['Easy Coach', 'Guardian Angel', 'Kisumu Direct Shuttles'],
    popularDropPoints: ['Siaya Town CBD', 'Bondo Stage (Near JOOUST)', 'Ugunja Junction', 'Yala Town', 'Usenge Beach'],
  },
  {
    code: '042',
    number: 42,
    name: 'Kisumu',
    capital: 'Kisumu City (Depot Headquarters)',
    primaryStage: 'Kisumu Main Bus Park, Stage Stand #4',
    region: 'Nyanza & Lake Basin',
    transitHours: 'Local Depot Dispatch (Instant Pickup)',
    recommendedCouriers: ['Depot Counter Collection', 'Local Kisumu Courier Boda', 'Direct Tuk-Tuk'],
    popularDropPoints: ['Kisumu Central Bus Park', 'Kondele Mega', 'Mega City Mall', 'Kenyatta Sports Ground Stage', 'Ahero Town'],
  },
  {
    code: '043',
    number: 43,
    name: 'Homa Bay',
    capital: 'Homa Bay Town / Oyugis',
    primaryStage: 'Homa Bay Pier Bus Park & Oyugis Stage',
    region: 'Nyanza & Lake Basin',
    transitHours: 'Immediate Direct (1.5 hrs from Kisumu)',
    recommendedCouriers: ['Easy Coach', 'Guardian Angel', 'Ena Coach', 'Kisumu Direct Shuttles'],
    popularDropPoints: ['Homa Bay Town Pier', 'Oyugis Central Stage', 'Mbita Point', 'Ndhiwa Town', 'Kendu Bay'],
  },
  {
    code: '044',
    number: 44,
    name: 'Migori',
    capital: 'Migori Town / Isebania',
    primaryStage: 'Migori Post Office Stage & Isebania Border Terminal',
    region: 'Nyanza & Lake Basin',
    transitHours: 'Direct Highway (2.5 - 3 hrs from Kisumu)',
    recommendedCouriers: ['Guardian Angel', 'Ena Coach', 'Easy Coach', 'Transline Classic'],
    popularDropPoints: ['Migori Town CBD Stage', 'Isebania Border Post', 'Rongo Town (Near Rongo Univ)', 'Awendo (Sony Sugar)', 'Kehancha'],
  },
  {
    code: '045',
    number: 45,
    name: 'Kisii',
    capital: 'Kisii Town',
    primaryStage: 'Kisii Town Sansora & Capital Roundabout Stage',
    region: 'Nyanza & Lake Basin',
    transitHours: 'Direct Express (1.5 - 2 hrs from Kisumu)',
    recommendedCouriers: ['Guardian Angel', 'Ena Coach', 'Easy Coach', 'Transline Classic', 'Otange Bus'],
    popularDropPoints: ['Kisii Sansora Area', 'Daraja Mbili Market', 'Ogembo Town', 'Suneka Stage', 'Keroka Town'],
  },
  {
    code: '046',
    number: 46,
    name: 'Nyamira',
    capital: 'Nyamira Town / Keroka',
    primaryStage: 'Nyamira Town Central Stage & Keroka Market',
    region: 'Nyanza & Lake Basin',
    transitHours: 'Direct Express (1.5 hrs from Kisumu)',
    recommendedCouriers: ['Guardian Angel', 'Ena Coach', 'Easy Coach', 'Transline Classic'],
    popularDropPoints: ['Nyamira Town CBD', 'Keroka High Street', 'Nyansiongo Stage', 'Manga Junction'],
  },

  // 047 Capital Hub
  {
    code: '047',
    number: 47,
    name: 'Nairobi City',
    capital: 'Nairobi CBD / Eastleigh / OTC',
    primaryStage: 'OTC / Tea Room / Machakos Country Bus Terminal',
    region: 'Nairobi & Central',
    transitHours: 'Daily 4:00 PM Express (Overnight 6-7 hrs)',
    recommendedCouriers: ['Guardian Angel', 'Easy Coach', 'Ena Coach', 'Transline Classic', 'Climax Coach'],
    popularDropPoints: ['Nairobi CBD (Tea Room / Accra Rd)', 'Eastleigh (First Ave Mall)', 'OTC / Machakos Country Bus', 'River Road Luggage Bay', 'Westlands / Ngara'],
  },
];

export const KENYA_REGIONAL_CORRIDORS = [
  'All 47 Counties',
  'Nyanza & Lake Basin',
  'Western Region',
  'North Rift & South Rift',
  'Nairobi & Central',
  'Mount Kenya & Eastern',
  'Coast Corridor',
  'North Eastern',
] as const;
