import { Product, Order, StoreSettings, ResellerProfitModel, StarterPack } from '../types';
import { INITIAL_47_COUNTIES_SHIPPING_RATES } from './kenyaCountiesData';

export const INITIAL_STORE_SETTINGS: StoreSettings = {
  shopName: 'Blues Collection Wholesale & Retail',
  locationAddress: 'Kisumu Main Bus Park, Central Stage Terminus',
  landmark: 'Directly at Kisumu Bus Park / Main Stage, Next to Guardian Angel & Easy Coach Offices',
  city: 'Kisumu',
  country: 'Kenya',
  kisumuPhone1: '+254 712 345 678',
  kisumuPhone2: '+254 722 987 654',
  whatsappNumber: '+254712345678',
  whatsappGroupUrl: 'https://chat.whatsapp.com/invite/BluesCollectionWholesaleVIP',
  mpesaPaybill: '522522',
  mpesaTill: '839201',
  kraPin: 'P051892401Z',
  workingHours: 'Mon - Sat: 7:30 AM - 7:00 PM (EAT) · Direct Bus Loading & Parcels Dispatched at 4:00 PM Sharp',
  shippingRates: INITIAL_47_COUNTIES_SHIPPING_RATES,
  fuelSurgeMultiplier: 1.0,
  fuelSurchargePerCarton: 0,
  fuelSurgeReason: 'Standard EPRA Diesel Tariff (Baseline 1.0x)',
  freeShippingEnabled: true,
  freeShippingThresholdPairs: 48,
};

export const RESELLER_TOWN_PROFILES: ResellerProfitModel[] = [
  { townName: 'Eldoret CBD & Uganda Rd', suggestedRetailPrice: 2800, estimatedPairsPerMonth: 120, localTransportPerPair: 50 },
  { townName: 'Nairobi Eastleigh & OTC', suggestedRetailPrice: 3000, estimatedPairsPerMonth: 250, localTransportPerPair: 70 },
  { townName: 'Kakamega Town Mega Mall', suggestedRetailPrice: 2700, estimatedPairsPerMonth: 90, localTransportPerPair: 40 },
  { townName: 'Bungoma Town Bus Park', suggestedRetailPrice: 2650, estimatedPairsPerMonth: 80, localTransportPerPair: 45 },
  { townName: 'Kisii Town Sansora Area', suggestedRetailPrice: 2750, estimatedPairsPerMonth: 110, localTransportPerPair: 45 },
  { townName: 'Kitale Town Commercial St', suggestedRetailPrice: 2700, estimatedPairsPerMonth: 75, localTransportPerPair: 60 },
  { townName: 'Kisumu Mega City / CBD', suggestedRetailPrice: 2800, estimatedPairsPerMonth: 140, localTransportPerPair: 20 },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-ladies-01',
    title: 'Monaco Comfort Block Heel Pumps',
    category: 'ladies',
    brand: 'Blues Elegance',
    description: 'High-demand Italian-style synthetic leather block heels for corporate and smart casual wear. Features cushioned inner soles and non-slip rubber outsoles. Mandatory paired distribution matrix enforced to balance reseller sizes.',
    retailPrice: 2800,
    wholesalePrice: 1550,
    buyingPrice: 950,
    wholesaleTiers: [
      { minQuantity: 2, pricePerUnit: 1550, label: 'Wholesale (2+ pairs)' },
    ],
    sizingRuleType: 'paired_ladies',
    pairingRules: [
      { primarySize: 42, requiredSize: 37, ratio: 1 },
      { primarySize: 41, requiredSize: 38, ratio: 1 },
      { primarySize: 40, requiredSize: 39, ratio: 1 },
    ],
    variants: [
      { id: 'v-37', size: 37, color: 'Nude Beige', sku: 'BLU-HEEL-37', stockQuantity: 64 },
      { id: 'v-38', size: 38, color: 'Nude Beige', sku: 'BLU-HEEL-38', stockQuantity: 82 },
      { id: 'v-39', size: 39, color: 'Nude Beige', sku: 'BLU-HEEL-39', stockQuantity: 90 },
      { id: 'v-40', size: 40, color: 'Nude Beige', sku: 'BLU-HEEL-40', stockQuantity: 85 },
      { id: 'v-41', size: 41, color: 'Nude Beige', sku: 'BLU-HEEL-41', stockQuantity: 78 },
      { id: 'v-42', size: 42, color: 'Nude Beige', sku: 'BLU-HEEL-42', stockQuantity: 55 },
    ],
    allowedColors: ['Nude Beige', 'Classic Black', 'Crimson Red', 'Ivory Cream'],
    imageUrl: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=800&q=80',
    isActive: true,
    moq: 2,
    has3DModel: true,
    defaultLowStockThreshold: 30,
    tag: 'Paired Ratio (42/37, 41/38, 40/39)',
    rating: 4.9,
    reviewCount: 3,
    reviews: [
      {
        id: 'rev-001',
        productId: 'prod-ladies-01',
        resellerName: 'Mama Stacy Footwear',
        resellerLocation: 'Kisumu County (Kibuye Market Depot)',
        rating: 5,
        reviewDate: '2026-09-20',
        title: 'Top seller for Sunday church & corporate wear in Kisumu!',
        comment: 'Sold out 2 full cartons (48 pairs) in just 5 days. Heel stability is superb and the size pairing rule 42↔37 completely prevented orphan sizes. Customers specifically ask for the Nude Beige colorway.',
        verifiedPurchase: true,
        businessType: 'Physical Boutique',
        pairsPurchased: 48,
        turnoverSpeed: 'Sold out within 5 days',
        helpfulCount: 14,
        orderNumberRef: 'BC-2026-8942',
        replyFromDepot: {
          author: 'Blues Kisumu Central Stage Depot',
          message: 'Thank you Mama Stacy! New batch of Nude Beige & Crimson Red has arrived at Swan Centre.',
          date: '2026-09-21',
        },
      },
      {
        id: 'rev-002',
        productId: 'prod-ladies-01',
        resellerName: 'Achieng Ouma (Mega Shoes)',
        resellerLocation: 'Uasin Gishu County (Eldoret CBD & Uganda Rd)',
        rating: 5,
        reviewDate: '2026-09-18',
        title: 'Arrived in Eldoret within 6 hours via Guardian Angel',
        comment: 'Dispatched from Kisumu Bus Park at 4:00 PM and arrived safely at Eldoret stage before 10:00 PM. High margins: bought at KSh 1,550 and sold out at KSh 2,800 retail.',
        verifiedPurchase: true,
        businessType: 'Wholesale Carton Merchant',
        pairsPurchased: 24,
        turnoverSpeed: 'Sold out within 1 week',
        helpfulCount: 9,
        orderNumberRef: 'BC-2026-9104',
      },
      {
        id: 'rev-003',
        productId: 'prod-ladies-01',
        resellerName: 'Brenda Chebet',
        resellerLocation: 'Kericho County (Kericho CBD Boutique)',
        rating: 5,
        reviewDate: '2026-09-14',
        title: 'Exceptional inner sole cushioning',
        comment: 'My clients who are teachers and bankers love that they can wear these block heels all day without foot fatigue. Will definitely reorder next week.',
        verifiedPurchase: true,
        businessType: 'Physical Boutique',
        pairsPurchased: 24,
        turnoverSpeed: 'Sold out within 1 week',
        helpfulCount: 6,
      },
    ],
  },
  {
    id: 'prod-ladies-02',
    title: 'Nairobi Chic Strappy Party Stiletto',
    category: 'ladies',
    brand: 'Blues Elegance',
    description: 'Glamorous metallic strap evening heels. Top seller among western Kenya boutique resellers. Enforces size 42↔37, 41↔38, 40↔39 inventory balance.',
    retailPrice: 3200,
    wholesalePrice: 1750,
    buyingPrice: 1050,
    wholesaleTiers: [
      { minQuantity: 2, pricePerUnit: 1750, label: 'Wholesale (2+ pairs)' },
    ],
    sizingRuleType: 'paired_ladies',
    pairingRules: [
      { primarySize: 42, requiredSize: 37, ratio: 1 },
      { primarySize: 41, requiredSize: 38, ratio: 1 },
      { primarySize: 40, requiredSize: 39, ratio: 1 },
    ],
    variants: [
      { id: 'v-s37', size: 37, color: 'Gold Sheen', sku: 'BLU-STRAP-37', stockQuantity: 40, lowStockThreshold: 30 },
      { id: 'v-s38', size: 38, color: 'Gold Sheen', sku: 'BLU-STRAP-38', stockQuantity: 52, lowStockThreshold: 30 },
      { id: 'v-s39', size: 39, color: 'Gold Sheen', sku: 'BLU-STRAP-39', stockQuantity: 48, lowStockThreshold: 30 },
      { id: 'v-s40', size: 40, color: 'Gold Sheen', sku: 'BLU-STRAP-40', stockQuantity: 50, lowStockThreshold: 30 },
      { id: 'v-s41', size: 41, color: 'Gold Sheen', sku: 'BLU-STRAP-41', stockQuantity: 42, lowStockThreshold: 30 },
      { id: 'v-s42', size: 42, color: 'Gold Sheen', sku: 'BLU-STRAP-42', stockQuantity: 28, lowStockThreshold: 35 },
    ],
    allowedColors: ['Gold Sheen', 'Midnight Silver', 'Rose Bronze', 'Glossy Black'],
    imageUrl: 'https://images.unsplash.com/photo-1535043934128-cf0b28d52f95?auto=format&fit=crop&w=800&q=80',
    isActive: true,
    moq: 2,
    defaultLowStockThreshold: 30,
    tag: 'Paired Ratio (42/37, 41/38, 40/39)',
    rating: 4.8,
    reviewCount: 2,
    reviews: [
      {
        id: 'rev-004',
        productId: 'prod-ladies-02',
        resellerName: 'Sharon Mwende',
        resellerLocation: 'Nakuru County (Section 58 Boutique)',
        rating: 5,
        reviewDate: '2026-09-19',
        title: 'Gold Sheen color is dazzling for bridal weddings',
        comment: 'Bridesmaids and party clients cleared 24 pairs in 4 days. Metallic straps are soft and do not pinch.',
        verifiedPurchase: true,
        businessType: 'Physical Boutique',
        pairsPurchased: 24,
        turnoverSpeed: 'Sold out within 4 days',
        helpfulCount: 7,
      },
      {
        id: 'rev-005',
        productId: 'prod-ladies-02',
        resellerName: 'Faith Atieno (Kisii Trendz)',
        resellerLocation: 'Kisii County (Sansora Mall)',
        rating: 4,
        reviewDate: '2026-09-12',
        title: 'Very glamorous, reordering for December season',
        comment: 'Great finish and sturdy heel. Fast bus parcel delivery to Kisii town via Guardian Angel.',
        verifiedPurchase: true,
        businessType: 'WhatsApp / Instagram Vendor',
        pairsPurchased: 12,
        turnoverSpeed: 'Sold out within 1 week',
        helpfulCount: 4,
      },
    ],
  },
  {
    id: 'prod-mens-01',
    title: 'Executive Italian Leather Loafers',
    category: 'mens',
    brand: 'Blues Sartorial',
    description: 'Hand-finished genuine calfskin leather slip-on shoes with durable Goodyear welt sole. Flexible open sizing allows resellers to select any combination of sizes 40 through 45 based on their local store demand.',
    retailPrice: 4200,
    wholesalePrice: 2200,
    buyingPrice: 1350,
    wholesaleTiers: [
      { minQuantity: 2, pricePerUnit: 2200, label: 'Wholesale (2+ pairs)' },
    ],
    sizingRuleType: 'flexible_mens',
    variants: [
      { id: 'v-m40', size: 40, color: 'Cognac Tan', sku: 'BLU-LOAF-40', stockQuantity: 45, lowStockThreshold: 30 },
      { id: 'v-m41', size: 41, color: 'Cognac Tan', sku: 'BLU-LOAF-41', stockQuantity: 60, lowStockThreshold: 30 },
      { id: 'v-m42', size: 42, color: 'Cognac Tan', sku: 'BLU-LOAF-42', stockQuantity: 80, lowStockThreshold: 30 },
      { id: 'v-m43', size: 43, color: 'Cognac Tan', sku: 'BLU-LOAF-43', stockQuantity: 75, lowStockThreshold: 30 },
      { id: 'v-m44', size: 44, color: 'Cognac Tan', sku: 'BLU-LOAF-44', stockQuantity: 50, lowStockThreshold: 30 },
      { id: 'v-m45', size: 45, color: 'Cognac Tan', sku: 'BLU-LOAF-45', stockQuantity: 22, lowStockThreshold: 30 },
    ],
    allowedColors: ['Cognac Tan', 'Classic Black', 'Deep Espresso', 'Dark Navy'],
    imageUrl: 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?auto=format&fit=crop&w=800&q=80',
    has3DModel: true,
    isActive: true,
    moq: 2,
    defaultLowStockThreshold: 30,
    tag: 'Flexible Sizing (40-45)',
    rating: 5.0,
    reviewCount: 2,
    reviews: [
      {
        id: 'rev-006',
        productId: 'prod-mens-01',
        resellerName: 'Kibet Kiprop',
        resellerLocation: 'Nandi County (Kapsabet Footwear Hub)',
        rating: 5,
        reviewDate: '2026-09-22',
        title: 'Huge demand among county government professionals',
        comment: 'Real calfskin leather at KSh 2,200 wholesale is unbeatable value. Sold at KSh 4,200 easily. Reordering Cognac Tan and Classic Black sizes 42 & 43.',
        verifiedPurchase: true,
        businessType: 'Physical Boutique',
        pairsPurchased: 36,
        turnoverSpeed: 'Sold out within 10 days',
        helpfulCount: 11,
        replyFromDepot: {
          author: 'Blues Sartorial Desk',
          message: 'Kapsabet hub orders receive direct North Rift shuttle parcel dispatch daily!',
          date: '2026-09-23',
        },
      },
      {
        id: 'rev-007',
        productId: 'prod-mens-01',
        resellerName: 'Dennis Otieno',
        resellerLocation: 'Nairobi County (Eastleigh 1st Ave Reseller)',
        rating: 5,
        reviewDate: '2026-09-17',
        title: 'Boutique customers compare it to KSh 7,000 shoes',
        comment: 'The stitching and sole welt are immaculate. Size 42 and 43 are the top movers for us.',
        verifiedPurchase: true,
        businessType: 'Wholesale Carton Merchant',
        pairsPurchased: 48,
        turnoverSpeed: 'Sold out within 1 week',
        helpfulCount: 8,
      },
    ],
  },
  {
    id: 'prod-sneakers-01',
    title: 'Blues Velocity Aerodynamic Runner',
    category: 'sneakers',
    brand: 'Blues Athletics',
    description: 'Ultra-lightweight breathable mesh street runner equipped with responsive air-cushion bounce. High turnover item in campus and urban towns. Compatible with 3D 360-degree interactive viewer and sole flex analysis.',
    retailPrice: 3500,
    wholesalePrice: 1900,
    buyingPrice: 1100,
    wholesaleTiers: [
      { minQuantity: 2, pricePerUnit: 1900, label: 'Wholesale (2+ pairs)' },
    ],
    sizingRuleType: 'flexible_mens',
    variants: [
      { id: 'v-s40', size: 40, color: 'Kisumu Blue', sku: 'BLU-RUN-40', stockQuantity: 40 },
      { id: 'v-s41', size: 41, color: 'Kisumu Blue', sku: 'BLU-RUN-41', stockQuantity: 70 },
      { id: 'v-s42', size: 42, color: 'Kisumu Blue', sku: 'BLU-RUN-42', stockQuantity: 95 },
      { id: 'v-s43', size: 43, color: 'Kisumu Blue', sku: 'BLU-RUN-43', stockQuantity: 90 },
      { id: 'v-s44', size: 44, color: 'Kisumu Blue', sku: 'BLU-RUN-44', stockQuantity: 60 },
      { id: 'v-s45', size: 45, color: 'Kisumu Blue', sku: 'BLU-RUN-45', stockQuantity: 35 },
    ],
    allowedColors: ['Kisumu Blue', 'Triple White', 'Midnight Black', 'Volt Green'],
    imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
    has3DModel: true,
    isActive: true,
    moq: 2,
    tag: '3D Interactive View · Flexible Sizing',
    rating: 4.9,
    reviewCount: 2,
    reviews: [
      {
        id: 'rev-008',
        productId: 'prod-sneakers-01',
        resellerName: 'Brian Wanjala',
        resellerLocation: 'Kakamega County (Kakamega Town Mega Mall)',
        rating: 5,
        reviewDate: '2026-09-24',
        title: 'MMUST university students loved the air cushion sole',
        comment: 'Super fast turnover among youth & athletes. The 3D viewer on this website helped me showcase the sole to customers on WhatsApp before ordering.',
        verifiedPurchase: true,
        businessType: 'WhatsApp / Instagram Vendor',
        pairsPurchased: 24,
        turnoverSpeed: 'Sold out within 3 days (Instant hit)',
        helpfulCount: 15,
      },
      {
        id: 'rev-009',
        productId: 'prod-sneakers-01',
        resellerName: 'Victor Korir',
        resellerLocation: 'Uasin Gishu County (Eldoret Rivatex Area)',
        rating: 5,
        reviewDate: '2026-09-16',
        title: 'Triple White and Kisumu Blue are instant sellers',
        comment: 'Very comfortable shoe for running and casual street style. Generates KSh 1,600 net profit per pair sold.',
        verifiedPurchase: true,
        businessType: 'Physical Boutique',
        pairsPurchased: 24,
        turnoverSpeed: 'Sold out within 1 week',
        helpfulCount: 5,
      },
    ],
  },
  {
    id: 'prod-boots-01',
    title: 'Mara Safari Heavy Duty Leather Boots',
    category: 'boots',
    brand: 'Blues Rugged',
    description: 'Rugged all-weather ankle boots designed for durability in Western Kenya terrain. Reinforced steel-toe cap and waterproof oil-tanned leather. Flexible sizing 40-45.',
    retailPrice: 4800,
    wholesalePrice: 2600,
    buyingPrice: 1650,
    wholesaleTiers: [
      { minQuantity: 2, pricePerUnit: 2600, label: 'Wholesale (2+ pairs)' },
    ],
    sizingRuleType: 'flexible_mens',
    variants: [
      { id: 'v-b40', size: 40, color: 'Dark Rust', sku: 'BLU-BOOT-40', stockQuantity: 35 },
      { id: 'v-b41', size: 41, color: 'Dark Rust', sku: 'BLU-BOOT-41', stockQuantity: 50 },
      { id: 'v-b42', size: 42, color: 'Dark Rust', sku: 'BLU-BOOT-42', stockQuantity: 65 },
      { id: 'v-b43', size: 43, color: 'Dark Rust', sku: 'BLU-BOOT-43', stockQuantity: 55 },
      { id: 'v-b44', size: 44, color: 'Dark Rust', sku: 'BLU-BOOT-44', stockQuantity: 40 },
      { id: 'v-b45', size: 45, color: 'Dark Rust', sku: 'BLU-BOOT-45', stockQuantity: 25 },
    ],
    allowedColors: ['Dark Rust', 'Desert Tan', 'Onyx Black'],
    imageUrl: 'https://images.unsplash.com/photo-1520639888713-7851133b1ed0?auto=format&fit=crop&w=800&q=80',
    isActive: true,
    moq: 2,
    tag: 'Flexible Sizing (40-45)',
    rating: 4.8,
    reviewCount: 1,
    reviews: [
      {
        id: 'rev-010',
        productId: 'prod-boots-01',
        resellerName: 'Captain Juma',
        resellerLocation: 'Trans Nzoia County (Kitale Commercial St)',
        rating: 5,
        reviewDate: '2026-09-21',
        title: 'Tough build quality for agricultural and site engineers',
        comment: 'The reinforced toe and waterproof leather hold up brilliantly against heavy mud and rocky paths. Premium margins for rural merchants.',
        verifiedPurchase: true,
        businessType: 'Wholesale Carton Merchant',
        pairsPurchased: 24,
        turnoverSpeed: 'Steady 2-week turnover',
        helpfulCount: 7,
      },
    ],
  },
  {
    id: 'prod-sandals-01',
    title: 'Lakeside Comfort Slide Sandals (Assorted Carton)',
    category: 'sandals',
    brand: 'Blues Comfort',
    description: 'Fast-moving waterproof EVA cushion slides for home, beach, and leisure. Sold as Free Size / Assorted cartons where cartons come pre-packed with balanced size distributions (no single number picking needed).',
    retailPrice: 1200,
    wholesalePrice: 600,
    buyingPrice: 320,
    wholesaleTiers: [
      { minQuantity: 2, pricePerUnit: 600, label: 'Wholesale (2+ pairs)' },
    ],
    sizingRuleType: 'free_size',
    variants: [
      { id: 'v-free', size: 'Free Size (Assorted)', color: 'Mixed Assorted', sku: 'BLU-SLIDE-ASSORT', stockQuantity: 350 },
    ],
    allowedColors: ['Navy Blue', 'Olive Green', 'Jet Black', 'Mixed Assorted'],
    imageUrl: 'https://images.unsplash.com/photo-1603808033192-082d6919d3e1?auto=format&fit=crop&w=800&q=80',
    isActive: true,
    moq: 2,
    tag: 'Free Size / No Matrix Required',
    rating: 4.9,
    reviewCount: 2,
    reviews: [
      {
        id: 'rev-011',
        productId: 'prod-sandals-01',
        resellerName: 'Mama Kevin',
        resellerLocation: 'Busia County (Busia Border Market)',
        rating: 5,
        reviewDate: '2026-09-23',
        title: 'Slides move at lightning speed at the border',
        comment: 'Sold out 120 pairs in 1 week at the border crossing. Doubled our capital in 7 days!',
        verifiedPurchase: true,
        businessType: 'Open Air Market Stall',
        pairsPurchased: 120,
        turnoverSpeed: 'Sold out within 3 days (Instant hit)',
        helpfulCount: 16,
      },
      {
        id: 'rev-012',
        productId: 'prod-sandals-01',
        resellerName: 'John Njuguna',
        resellerLocation: 'Nairobi County (Gikomba Wholesale Depot)',
        rating: 5,
        reviewDate: '2026-09-15',
        title: 'Assorted master cartons have perfect size balance',
        comment: 'Zero dead stock. The mix contains just the right ratio of standard adult foot sizes.',
        verifiedPurchase: true,
        businessType: 'Wholesale Carton Merchant',
        pairsPurchased: 200,
        turnoverSpeed: 'Sold out within 1 week',
        helpfulCount: 9,
      },
    ],
  },
  {
    id: 'prod-ladies-03',
    title: 'Victoria Comfort Wedge Pumps',
    category: 'ladies',
    brand: 'Blues Elegance',
    description: 'All-day comfort wedge heel pumps crafted for teachers, nurses, and office professionals. Non-slip grooved rubber base. Strict ladies paired sizing 42↔37, 41↔38, 40↔39 enforced.',
    retailPrice: 2600,
    wholesalePrice: 1400,
    buyingPrice: 850,
    wholesaleTiers: [
      { minQuantity: 2, pricePerUnit: 1400, label: 'Wholesale (2+ pairs)' },
    ],
    sizingRuleType: 'paired_ladies',
    pairingRules: [
      { primarySize: 42, requiredSize: 37, ratio: 1 },
      { primarySize: 41, requiredSize: 38, ratio: 1 },
      { primarySize: 40, requiredSize: 39, ratio: 1 },
    ],
    variants: [
      { id: 'v-w37', size: 37, color: 'Midnight Black', sku: 'BLU-WDG-37', stockQuantity: 50 },
      { id: 'v-w38', size: 38, color: 'Midnight Black', sku: 'BLU-WDG-38', stockQuantity: 70 },
      { id: 'v-w39', size: 39, color: 'Midnight Black', sku: 'BLU-WDG-39', stockQuantity: 80 },
      { id: 'v-w40', size: 40, color: 'Midnight Black', sku: 'BLU-WDG-40', stockQuantity: 75 },
      { id: 'v-w41', size: 41, color: 'Midnight Black', sku: 'BLU-WDG-41', stockQuantity: 65 },
      { id: 'v-w42', size: 42, color: 'Midnight Black', sku: 'BLU-WDG-42', stockQuantity: 45 },
    ],
    allowedColors: ['Midnight Black', 'Warm Taupe', 'Navy Blue'],
    imageUrl: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=800&q=80',
    isActive: true,
    moq: 2,
    tag: 'Paired Ratio (42/37, 41/38, 40/39)',
  },
  {
    id: 'prod-mens-02',
    title: 'Milimani Formal Derby Brogues',
    category: 'mens',
    brand: 'Blues Sartorial',
    description: 'Laser-perforated Oxford brogue dress shoes with hand-burnished toe caps. Favored by corporate professionals and event occasions. Flexible reseller size distribution (sizes 40 to 45).',
    retailPrice: 4500,
    wholesalePrice: 2400,
    buyingPrice: 1500,
    wholesaleTiers: [
      { minQuantity: 2, pricePerUnit: 2400, label: 'Wholesale (2+ pairs)' },
    ],
    sizingRuleType: 'flexible_mens',
    variants: [
      { id: 'v-db40', size: 40, color: 'Dark Espresso', sku: 'BLU-BROG-40', stockQuantity: 30 },
      { id: 'v-db41', size: 41, color: 'Dark Espresso', sku: 'BLU-BROG-41', stockQuantity: 50 },
      { id: 'v-db42', size: 42, color: 'Dark Espresso', sku: 'BLU-BROG-42', stockQuantity: 75 },
      { id: 'v-db43', size: 43, color: 'Dark Espresso', sku: 'BLU-BROG-43', stockQuantity: 65 },
      { id: 'v-db44', size: 44, color: 'Dark Espresso', sku: 'BLU-BROG-44', stockQuantity: 45 },
      { id: 'v-db45', size: 45, color: 'Dark Espresso', sku: 'BLU-BROG-45', stockQuantity: 25 },
    ],
    allowedColors: ['Dark Espresso', 'Oxford Tan', 'Obsidian Black'],
    imageUrl: 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?auto=format&fit=crop&w=800&q=80',
    isActive: true,
    moq: 2,
    tag: 'Flexible Sizing (40-45)',
  }
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-001',
    orderNumber: 'BC-2026-9104',
    customerName: 'Achieng Ouma (Mega Shoes)',
    customerPhone: '0714987654',
    deliveryTown: 'Uasin Gishu County (Eldoret CBD & Uganda Rd)',
    deliveryType: 'parcel_delivery',
    courier: 'Guardian Angel',
    items: [
      {
        productId: 'prod-ladies-01',
        productTitle: 'Monaco Comfort Block Heel Pumps',
        size: 42,
        color: 'Nude Beige',
        quantity: 12,
        unitPrice: 1550,
        totalPrice: 18600,
        unitBuyingPrice: 950,
        totalCost: 11400,
        itemProfit: 7200,
      },
      {
        productId: 'prod-ladies-01',
        productTitle: 'Monaco Comfort Block Heel Pumps',
        size: 37,
        color: 'Nude Beige',
        quantity: 12,
        unitPrice: 1550,
        totalPrice: 18600,
        unitBuyingPrice: 950,
        totalCost: 11400,
        itemProfit: 7200,
      },
    ],
    subtotal: 67200,
    wholesaleSavings: 30000,
    totalAmount: 37200,
    totalCost: 22800,
    netProfit: 14400,
    profitMarginPct: 38.7,
    paymentMethod: 'mpesa_till',
    paymentStatus: 'paid',
    mpesaReceipt: 'TK94G6H21A',
    kraEtimSerial: 'ETIMS-KE-2026-00918',
    status: 'dispatched',
    waybillNumber: 'GA-ELD-49210',
    notes: 'Paired order verified (12 pairs Size 42 + 12 pairs Size 37). Dispatched via Guardian Angel Eldoret morning parcel bus.',
    createdAt: '2026-09-24T14:30:00Z',
    orderType: 'wholesale',
  },
  {
    id: 'ord-002',
    orderNumber: 'BC-2026-9105',
    customerName: 'Kiprono Rotich (Kakamega Styles)',
    customerPhone: '0722334455',
    deliveryTown: 'Kakamega County (Kakamega Town Mega Mall)',
    deliveryType: 'parcel_delivery',
    courier: 'Easy Coach',
    items: [
      {
        productId: 'prod-mens-01',
        productTitle: 'Executive Italian Leather Loafers',
        size: 42,
        color: 'Cognac Tan',
        quantity: 8,
        unitPrice: 2200,
        totalPrice: 17600,
        unitBuyingPrice: 1350,
        totalCost: 10800,
        itemProfit: 6800,
      },
      {
        productId: 'prod-mens-01',
        productTitle: 'Executive Italian Leather Loafers',
        size: 43,
        color: 'Cognac Tan',
        quantity: 8,
        unitPrice: 2200,
        totalPrice: 17600,
        unitBuyingPrice: 1350,
        totalCost: 10800,
        itemProfit: 6800,
      },
    ],
    subtotal: 67200,
    wholesaleSavings: 32000,
    totalAmount: 35200,
    totalCost: 21600,
    netProfit: 13600,
    profitMarginPct: 38.6,
    depositAmount: 10560,
    balanceDue: 24640,
    paymentMethod: 'lipa_pole_pole',
    paymentStatus: 'deposit_paid',
    mpesaReceipt: 'TK95A3K89F',
    kraEtimSerial: 'ETIMS-KE-2026-00921',
    status: 'packing',
    waybillNumber: 'EC-KKG-89301',
    notes: 'Lipa Pole Pole 30% deposit received (KSh 10,560). Balance KSh 24,640 due upon collection at Easy Coach Kakamega.',
    createdAt: '2026-09-25T08:15:00Z',
    orderType: 'wholesale',
  },
  {
    id: 'ord-003',
    orderNumber: 'BC-2026-9106',
    customerName: 'Brian Otieno (Lakeside Retailers)',
    customerPhone: '0701234567',
    deliveryTown: 'Kisumu County (Kisumu Mega City / CBD)',
    deliveryType: 'shop_pickup',
    courier: 'Direct Shop Pickup',
    items: [
      {
        productId: 'prod-sneakers-01',
        productTitle: 'Blues Velocity Aerodynamic Runner',
        size: 42,
        color: 'Kisumu Blue',
        quantity: 6,
        unitPrice: 1900,
        totalPrice: 11400,
        unitBuyingPrice: 1100,
        totalCost: 6600,
        itemProfit: 4800,
      },
      {
        productId: 'prod-sneakers-01',
        productTitle: 'Blues Velocity Aerodynamic Runner',
        size: 43,
        color: 'Kisumu Blue',
        quantity: 6,
        unitPrice: 1900,
        totalPrice: 11400,
        unitBuyingPrice: 1100,
        totalCost: 6600,
        itemProfit: 4800,
      }
    ],
    subtotal: 42000,
    wholesaleSavings: 19200,
    totalAmount: 22800,
    totalCost: 13200,
    netProfit: 9600,
    profitMarginPct: 42.1,
    paymentMethod: 'mpesa_stk',
    paymentStatus: 'paid',
    mpesaReceipt: 'TK95L9P11B',
    kraEtimSerial: 'ETIMS-KE-2026-00925',
    status: 'packing',
    waybillNumber: 'BUSPK-4109',
    notes: 'Packaging 12 pairs in Kisumu Bus Park main depot showroom. Ready for collection.',
    createdAt: '2026-09-25T09:40:00Z',
    orderType: 'wholesale',
  }
];

export const STARTER_RESELLER_PACKS: StarterPack[] = [
  {
    id: 'pack-kibuye-ladies-24',
    title: 'Kibuye Market Fast-Mover Ladies Heel Starter Pack',
    badge: '🔥 #1 Best Seller for Boutiques',
    category: 'ladies',
    targetMerchant: 'Physical Town Boutiques & Sunday Church Stalls',
    description: 'A pre-balanced 24-pair master carton of our top-moving Monaco Block Heels & Starlight Evening Sandals. Enforces genuine 42↔37, 41↔38, 40↔39 paired ratios to guarantee zero unsellable sizes.',
    totalPairs: 24,
    totalCartons: 1,
    bundleWholesalePrice: 35500,
    originalWholesalePrice: 38200,
    bundleDiscountPct: 7.1,
    suggestedRetailRevenue: 67200,
    estimatedNetProfit: 31700,
    expectedTurnoverDays: '4 - 7 Days',
    marginPct: 47.2,
    highlights: [
      'Zero dead stock: 100% paired ratio (Size 37-42)',
      'High Sunday church & corporate weekday demand',
      'Tested via Easy Coach & Guardian bus parcel parceling',
      'Net profit KSh 31,700 on 1 master carton'
    ],
    recommendedCounties: ['Kisumu', 'Uasin Gishu', 'Kakamega', 'Kericho', 'Nakuru', 'Nairobi'],
    includedItems: [
      {
        productId: 'prod-ladies-01',
        productTitle: 'Monaco Comfort Block Heel Pumps',
        imageUrl: 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=800&q=80',
        color: 'Nude Beige',
        pairs: 12,
        sizeBreakdown: { '37': 2, '38': 2, '39': 2, '40': 2, '41': 2, '42': 2 },
      },
      {
        productId: 'prod-ladies-02',
        productTitle: 'Starlight Ankle Strap Evening Sandal',
        imageUrl: 'https://images.unsplash.com/photo-1535043934128-cf0b28d52f95?auto=format&fit=crop&w=800&q=80',
        color: 'Gold Sheen',
        pairs: 12,
        sizeBreakdown: { '37': 2, '38': 2, '39': 2, '40': 2, '41': 2, '42': 2 },
      },
    ],
  },
  {
    id: 'pack-campus-runners-36',
    title: 'Western Campus Streetwear & Runner Drop Pack',
    badge: '⚡ Instant Youth Hit',
    category: 'sneakers',
    targetMerchant: 'WhatsApp / Instagram Vendors & Campus Boutiques (Maseno, MMUST, Moi, UoN)',
    description: 'High-turnover 36-pair athletic sneaker assortment engineered with impact air-cushions. Top-selling Triple White & Kisumu Blue colorways that sell rapidly to university students and casual lifestyle buyers.',
    totalPairs: 36,
    totalCartons: 1.5,
    bundleWholesalePrice: 64800,
    originalWholesalePrice: 68400,
    bundleDiscountPct: 5.3,
    suggestedRetailRevenue: 126000,
    estimatedNetProfit: 61200,
    expectedTurnoverDays: '3 - 5 Days',
    marginPct: 48.6,
    highlights: [
      'Massive campus demand with ~KSh 1,700 margin per pair',
      'Includes 3D model interactive previews for WhatsApp sharing',
      'Key sizes 40, 41, 42, 43, 44 included',
      'Projected net resale profit: KSh 61,200'
    ],
    recommendedCounties: ['Kisumu', 'Kakamega', 'Uasin Gishu', 'Nairobi', 'Bungoma', 'Nandi'],
    includedItems: [
      {
        productId: 'prod-sneakers-01',
        productTitle: 'Blues Velocity Aerodynamic Runner',
        imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
        color: 'Triple White',
        pairs: 18,
        sizeBreakdown: { '40': 3, '41': 4, '42': 5, '43': 4, '44': 2 },
      },
      {
        productId: 'prod-sneakers-01',
        productTitle: 'Blues Velocity Aerodynamic Runner',
        imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
        color: 'Kisumu Blue',
        pairs: 18,
        sizeBreakdown: { '40': 3, '41': 4, '42': 5, '43': 4, '44': 2 },
      },
    ],
  },
  {
    id: 'pack-executive-mens-24',
    title: 'Lake Basin Executive Leather Loafer Pack',
    badge: '👑 Premium County Pro Margin',
    category: 'mens',
    targetMerchant: 'CBD Men’s Boutiques & Corporate Sartorial Stores',
    description: 'Genuine calfskin leather formal loafers and brogues. Tailored for county government professionals, bankers, teachers, and lawyers in Western & Rift Valley urban hubs.',
    totalPairs: 24,
    totalCartons: 1,
    bundleWholesalePrice: 49500,
    originalWholesalePrice: 52800,
    bundleDiscountPct: 6.25,
    suggestedRetailRevenue: 100800,
    estimatedNetProfit: 51300,
    expectedTurnoverDays: '7 - 12 Days',
    marginPct: 50.9,
    highlights: [
      'Handcrafted genuine calfskin leather with Goodyear-style welt',
      'Sells at KSh 4,200 retail with huge KSh 2,000+ margin per pair',
      'Balanced men sizes 40 through 45',
      'Net profit KSh 51,300 per pack'
    ],
    recommendedCounties: ['Kisumu', 'Nairobi', 'Uasin Gishu', 'Kericho', 'Trans Nzoia', 'Nakuru'],
    includedItems: [
      {
        productId: 'prod-mens-01',
        productTitle: 'Oxford Executive Calfskin Loafer',
        imageUrl: 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?auto=format&fit=crop&w=800&q=80',
        color: 'Cognac Tan',
        pairs: 12,
        sizeBreakdown: { '40': 2, '41': 2, '42': 3, '43': 3, '44': 2 },
      },
      {
        productId: 'prod-mens-01',
        productTitle: 'Oxford Executive Calfskin Loafer',
        imageUrl: 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?auto=format&fit=crop&w=800&q=80',
        color: 'Classic Black',
        pairs: 12,
        sizeBreakdown: { '40': 2, '41': 2, '42': 3, '43': 3, '44': 2 },
      },
    ],
  },
  {
    id: 'pack-border-slides-60',
    title: 'Busia & Malaba Border High-Turnover Slide Bundle',
    badge: '🚀 High-Volume Rapid Cash',
    category: 'sandals',
    targetMerchant: 'Open Air Market Merchants (Busia, Kibuye, Kongowea, Gikomba)',
    description: 'Massive 60-pair assorted master crate of cushioned waterproof slide sandals. Free-size fast clearance with zero sizing matrix restrictions, perfect for high-traffic border traders.',
    totalPairs: 60,
    totalCartons: 1,
    bundleWholesalePrice: 39000,
    originalWholesalePrice: 42000,
    bundleDiscountPct: 7.14,
    suggestedRetailRevenue: 84000,
    estimatedNetProfit: 45000,
    expectedTurnoverDays: '3 - 6 Days',
    marginPct: 53.6,
    highlights: [
      'Free Size / No complex pairing needed',
      'Doubles your capital in 5-7 days',
      'Lightweight parcel shipping rates via Busia & Malaba shuttles',
      'Net profit KSh 45,000 on 60 pairs'
    ],
    recommendedCounties: ['Busia', 'Kisumu', 'Nairobi', 'Mombasa', 'Migori', 'Homa Bay'],
    includedItems: [
      {
        productId: 'prod-sandals-01',
        productTitle: 'Lake Breeze Cushioned Slide Sandals',
        imageUrl: 'https://images.unsplash.com/photo-1603808033192-082d6919d3e1?auto=format&fit=crop&w=800&q=80',
        color: 'Onyx Black',
        pairs: 30,
        sizeBreakdown: { '37': 4, '38': 6, '39': 8, '40': 6, '41': 4, '42': 2 },
      },
      {
        productId: 'prod-sandals-01',
        productTitle: 'Lake Breeze Cushioned Slide Sandals',
        imageUrl: 'https://images.unsplash.com/photo-1603808033192-082d6919d3e1?auto=format&fit=crop&w=800&q=80',
        color: 'Navy Blue',
        pairs: 30,
        sizeBreakdown: { '37': 4, '38': 6, '39': 8, '40': 6, '41': 4, '42': 2 },
      },
    ],
  },
  {
    id: 'pack-safari-boots-24',
    title: 'Trans-Nzoia & Rift Valley Rugged Safari Boot Crate',
    badge: '🛡️ Heavy-Duty Workhorse',
    category: 'boots',
    targetMerchant: 'Agricultural & Field Gear Merchants (Kitale, Eldoret, Narok, Nanyuki)',
    description: 'Heavy-duty oiled leather boots built for durability in mud, tea plantations, and field inspection. High ticket item with superb customer satisfaction.',
    totalPairs: 24,
    totalCartons: 1,
    bundleWholesalePrice: 62000,
    originalWholesalePrice: 67200,
    bundleDiscountPct: 7.74,
    suggestedRetailRevenue: 115200,
    estimatedNetProfit: 53200,
    expectedTurnoverDays: '10 - 18 Days',
    marginPct: 46.2,
    highlights: [
      'Oil-resistant non-slip lug tread with water-resistant leather',
      'KSh 2,200+ profit margin per boot sold',
      'Includes sizes 40 through 45',
      'Net profit KSh 53,200'
    ],
    recommendedCounties: ['Trans Nzoia', 'Uasin Gishu', 'Kericho', 'Nakuru', 'Narok', 'Baringo'],
    includedItems: [
      {
        productId: 'prod-boots-01',
        productTitle: 'Mara Rugged Leather Safari Boot',
        imageUrl: 'https://images.unsplash.com/photo-1520639888713-7851133b1ed0?auto=format&fit=crop&w=800&q=80',
        color: 'Earth Brown',
        pairs: 12,
        sizeBreakdown: { '40': 2, '41': 2, '42': 3, '43': 3, '44': 2 },
      },
      {
        productId: 'prod-boots-01',
        productTitle: 'Mara Rugged Leather Safari Boot',
        imageUrl: 'https://images.unsplash.com/photo-1520639888713-7851133b1ed0?auto=format&fit=crop&w=800&q=80',
        color: 'Desert Sand',
        pairs: 12,
        sizeBreakdown: { '40': 2, '41': 2, '42': 3, '43': 3, '44': 2 },
      },
    ],
  },
];

